name: Build EXE file

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller
    - name: Build pyinstaller
      run: pyinstaller --onefile --noconsole game/run.py -n snake
    - uses: actions/upload-artifact@v2
      with:
        name: exe
        path: dist/snake.exe
